    dll.insert("A")
    dll.insert("B")
    dll.insert("C")
    dll.insert("D")
    dll.insert("E")
    dll.move_to_next()
    dll.move_to_next()
    dll.insert("1")
    dll.insert("2")
    dll.move_to_next()
    dll.insert("3")
    dll.insert("4")
    dll.move_to_prev()
    dll.insert("VALUE")
    dll.move_to_pos(8)
    dll.remove()
    dll.remove()
    dll.remove()
    dll.move_to_pos(2)
    dll.remove()
    dll.remove()
    dll.remove()
    dll.move_to_prev()
    dll.move_to_prev()
    dll.move_to_prev()
    dll.move_to_prev()
    dll.move_to_prev()
    dll.move_to_prev()
    dll.remove()
    dll.remove()
    dll.move_to_next()
    dll.move_to_next()
    dll.move_to_next()
    dll.move_to_next()
    dll.remove()
    dll.move_to_pos(-1)
    dll.move_to_pos(18)
    dll.move_to_pos(0)
    dll.remove()
    dll.remove()
    dll.remove()
    dll.remove()


    
    
    
    
    print("\n\nTESTING MORE COMPLEX STUFF\n")

    dll.insert("A")
    dll.insert("B1")
    dll.insert("C")
    dll.insert("A")
    dll.insert("B2")
    dll.partition(dll.get_first_node(), dll.get_last_node())
    dll.insert("C")
    dll.insert("A")
    result = dll.get_first_node()
    if result != None:
        result = result.data
    print("first node: ", str(result))
    dll.insert("B3")
    dll.insert("C")
    result = dll.get_last_node()
    if result != None:
        result = result.data
    print("last node: ", str(result))
    dll.move_to_pos(0)
    dll.insert("B5")
    dll.move_to_pos(4)
    dll.partition(dll.get_first_node(), dll.get_last_node())
    dll.sort()

    dll.clear()
    

    dll.insert("B")
    dll.insert("D")
    dll.insert("G")
    dll.insert("T")
    dll.insert("A")
    dll.insert("C")
    dll.insert("B")
    dll.move_to_next()
    dll.remove()
    dll.remove()
    dll.remove()
    dll.remove()
    result = dll.get_first_node()
    if result != None:
        result = result.data
    print("first node: ", str(result))
    dll.move_to_prev()
    dll.move_to_prev()
    dll.remove()
    result = dll.get_last_node()
    if result != None:
        result = result.data
    print("last node: ", str(result))
    dll.clear()
