from array_list import ArrayList

arr = ArrayList()

arr.insert_ordered(10)
arr.insert_ordered(11)
arr.insert_ordered(12)
arr.insert_ordered(13)
arr.insert_ordered(13)
arr.insert_ordered(13)
arr.insert_ordered(14)
arr.insert_ordered(15)
arr.insert_ordered(15)
arr.insert_ordered(16)
arr.insert_ordered(18)
arr.insert_ordered(18)
arr.insert_ordered(18)
arr.insert_ordered(19)
arr.insert_ordered(21)
arr.insert_ordered(21)
arr.insert_ordered(22)
arr.insert_ordered(22)
arr.insert_ordered(23)
arr.insert_ordered(23)
arr.insert_ordered(24)
arr.insert_ordered(24)
arr.insert_ordered(25)
arr.insert_ordered(27)
arr.insert_ordered(28)
arr.insert_ordered(28)
arr.insert_ordered(28)
arr.insert_ordered(29)
arr.insert_ordered(29)
arr.insert_ordered(29)
arr.insert_ordered(29)
arr.insert_ordered(30)

arr.find(13)
